// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Data;

#nullable disable

namespace server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809051153_AddAiBulkGenerationMonthlyUsage")]
    partial class AddAiBulkGenerationMonthlyUsage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.Data.Entities.AiBulkGenerationMonthlyUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date")
                        .HasColumnName("month");

                    b.HasKey("Id")
                        .HasName("pk_ai_bulk_generation_monthly_usage");

                    b.HasIndex("Month")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_bulk_generation_monthly_usage_month");

                    b.ToTable("ai_bulk_generation_monthly_usage", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_class");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_class_updated_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_class_user_id");

                    b.ToTable("class", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.ClassTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_class_template");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_class_template_updated_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_class_template_user_id");

                    b.ToTable("class_template", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.ClassTemplateLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassTemplateSubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_template_subject_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("LessonInUnit")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_in_unit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Unit")
                        .HasColumnType("integer")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_class_template_lesson");

                    b.HasIndex("ClassTemplateSubjectId")
                        .HasDatabaseName("ix_class_template_lesson_class_template_subject_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_class_template_lesson_updated_at");

                    b.ToTable("class_template_lesson", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.ClassTemplateSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_template_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_class_template_subject");

                    b.HasIndex("ClassTemplateId")
                        .HasDatabaseName("ix_class_template_subject_class_template_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_class_template_subject_updated_at");

                    b.ToTable("class_template_subject", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("LessonInUnit")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_in_unit");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Unit")
                        .HasColumnType("integer")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lesson");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_lesson_updated_at");

                    b.HasIndex("SubjectId", "Unit", "LessonInUnit")
                        .IsUnique()
                        .HasDatabaseName("ix_lesson_subject_id_unit_lesson_in_unit");

                    b.ToTable("lesson", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.Progress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("StepClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_client_id");

                    b.Property<string>("StepHlc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step_hlc");

                    b.Property<int>("StepLessonInUnit")
                        .HasColumnType("integer")
                        .HasColumnName("step_lesson_in_unit");

                    b.Property<int>("StepUnit")
                        .HasColumnType("integer")
                        .HasColumnName("step_unit");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_progress");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_progress_subject_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_progress_updated_at");

                    b.HasIndex("StudentId", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_progress_student_id_subject_id");

                    b.ToTable("progress", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.ReviewFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<bool>("Flagged")
                        .HasColumnType("boolean")
                        .HasColumnName("flagged");

                    b.Property<string>("Hlc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hlc");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_review_flag");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_review_flag_lesson_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_review_flag_updated_at");

                    b.HasIndex("StudentId", "LessonId")
                        .IsUnique()
                        .HasDatabaseName("ix_review_flag_student_id_lesson_id");

                    b.ToTable("review_flag", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_student");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_student_class_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_student_updated_at");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subject");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_subject_class_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_subject_updated_at");

                    b.ToTable("subject", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.SubjectTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_subject_template");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_subject_template_updated_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_subject_template_user_id");

                    b.ToTable("subject_template", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.SubjectTemplateLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("LessonInUnit")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_in_unit");

                    b.Property<Guid>("SubjectTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Unit")
                        .HasColumnType("integer")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subject_template_lesson");

                    b.HasIndex("SubjectTemplateId")
                        .HasDatabaseName("ix_subject_template_lesson_subject_template_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_subject_template_lesson_updated_at");

                    b.ToTable("subject_template_lesson", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleSub")
                        .HasColumnType("text")
                        .HasColumnName("google_sub");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_demo");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("GoogleSub")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_sub");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.Class", b =>
                {
                    b.HasOne("server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_users_user_id");
                });

            modelBuilder.Entity("server.Data.Entities.ClassTemplate", b =>
                {
                    b.HasOne("server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_template_users_user_id");
                });

            modelBuilder.Entity("server.Data.Entities.ClassTemplateLesson", b =>
                {
                    b.HasOne("server.Data.Entities.ClassTemplateSubject", null)
                        .WithMany()
                        .HasForeignKey("ClassTemplateSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_template_lesson_class_template_subject_class_template");
                });

            modelBuilder.Entity("server.Data.Entities.ClassTemplateSubject", b =>
                {
                    b.HasOne("server.Data.Entities.ClassTemplate", null)
                        .WithMany()
                        .HasForeignKey("ClassTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_template_subject_class_template_class_template_id");
                });

            modelBuilder.Entity("server.Data.Entities.Lesson", b =>
                {
                    b.HasOne("server.Data.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_subject_subject_id");
                });

            modelBuilder.Entity("server.Data.Entities.Progress", b =>
                {
                    b.HasOne("server.Data.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_progress_student_student_id");

                    b.HasOne("server.Data.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_progress_subject_subject_id");
                });

            modelBuilder.Entity("server.Data.Entities.ReviewFlag", b =>
                {
                    b.HasOne("server.Data.Entities.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_review_flag_lesson_lesson_id");

                    b.HasOne("server.Data.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_review_flag_student_student_id");
                });

            modelBuilder.Entity("server.Data.Entities.Student", b =>
                {
                    b.HasOne("server.Data.Entities.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_class_class_id");
                });

            modelBuilder.Entity("server.Data.Entities.Subject", b =>
                {
                    b.HasOne("server.Data.Entities.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subject_class_class_id");
                });

            modelBuilder.Entity("server.Data.Entities.SubjectTemplate", b =>
                {
                    b.HasOne("server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subject_template_users_user_id");
                });

            modelBuilder.Entity("server.Data.Entities.SubjectTemplateLesson", b =>
                {
                    b.HasOne("server.Data.Entities.SubjectTemplate", null)
                        .WithMany()
                        .HasForeignKey("SubjectTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subject_template_lesson_subject_template_subject_template_id");
                });
#pragma warning restore 612, 618
        }
    }
}
