// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Data;

#nullable disable

namespace server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.Data.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_class");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_class_user_id");

                    b.ToTable("class", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("LessonInUnit")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_in_unit");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Unit")
                        .HasColumnType("integer")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_lesson");

                    b.HasIndex("SubjectId", "Unit", "LessonInUnit")
                        .IsUnique()
                        .HasDatabaseName("ix_lesson_subject_id_unit_lesson_in_unit");

                    b.ToTable("lesson", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.Progress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Review")
                        .HasColumnType("boolean")
                        .HasColumnName("review");

                    b.Property<Guid>("ReviewClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_client_id");

                    b.Property<string>("ReviewHlc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review_hlc");

                    b.Property<Guid>("StepClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_client_id");

                    b.Property<string>("StepHlc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step_hlc");

                    b.Property<int>("StepLessonInUnit")
                        .HasColumnType("integer")
                        .HasColumnName("step_lesson_in_unit");

                    b.Property<int>("StepUnit")
                        .HasColumnType("integer")
                        .HasColumnName("step_unit");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.HasKey("Id")
                        .HasName("pk_progress");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_progress_subject_id");

                    b.HasIndex("StudentId", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_progress_student_id_subject_id");

                    b.ToTable("progress", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_student");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_student_class_id");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_subject");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_subject_class_id");

                    b.ToTable("subject", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleSub")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("google_sub");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("GoogleSub")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_sub");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("server.Data.Entities.Class", b =>
                {
                    b.HasOne("server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_users_user_id");
                });

            modelBuilder.Entity("server.Data.Entities.Lesson", b =>
                {
                    b.HasOne("server.Data.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_subject_subject_id");
                });

            modelBuilder.Entity("server.Data.Entities.Progress", b =>
                {
                    b.HasOne("server.Data.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_progress_student_student_id");

                    b.HasOne("server.Data.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_progress_subject_subject_id");
                });

            modelBuilder.Entity("server.Data.Entities.Student", b =>
                {
                    b.HasOne("server.Data.Entities.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_class_class_id");
                });

            modelBuilder.Entity("server.Data.Entities.Subject", b =>
                {
                    b.HasOne("server.Data.Entities.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subject_class_class_id");
                });
#pragma warning restore 612, 618
        }
    }
}
